In [1]:
import warnings
warnings.filterwarnings('ignore')

import shap 
from sklearn.model_selection import train_test_split
import pandas as pd

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

## 보스턴 데이터
data = pd.read_csv("https://blog.kakaocdn.net/dn/xjHHl/btsvj90VSNh/Pjhm2ucmtqgEuXqjnrV2q0/boston_data.csv?attach=1&knm=tfile.csv")
df = data[data.columns[:-1]]
X = df
X_features = X.columns[:-1]

y = data['MEDV']

X.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [2]:
X_train, X_test, y_train, y_test = train_test_split(df[X_features], 
                                                    df['MEDV'], 
                                                    test_size=0.2, 
                                                    random_state=1)

In [3]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [4]:
X_train

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
42,0.14150,0.0,6.91,0,0.448,6.169,6.6,5.7209,3,233,17.9,383.37,5.81
58,0.15445,25.0,5.13,0,0.453,6.145,29.2,7.8148,8,284,19.7,390.68,6.86
385,16.81180,0.0,18.10,0,0.700,5.277,98.1,1.4261,24,666,20.2,396.90,30.81
78,0.05646,0.0,12.83,0,0.437,6.232,53.7,5.0141,5,398,18.7,386.40,12.34
424,8.79212,0.0,18.10,0,0.584,5.565,70.6,2.0635,24,666,20.2,3.65,17.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,0.03548,80.0,3.64,0,0.392,5.876,19.1,9.2203,1,315,16.4,395.18,9.25
72,0.09164,0.0,10.81,0,0.413,6.065,7.8,5.2873,4,305,19.2,390.91,5.52
396,5.87205,0.0,18.10,0,0.693,6.405,96.0,1.6768,24,666,20.2,396.90,19.37
235,0.33045,0.0,6.20,0,0.507,6.086,61.5,3.6519,8,307,17.4,376.75,10.88
37,0.08014,0.0,5.96,0,0.499,5.850,41.5,3.9342,5,279,19.2,396.90,8.77

In [6]:
y_train

42     25.3
58     23.3
385     7.2
78     21.2
424    11.7
       ...
255    20.9
72     22.8
396    12.5
235    24.0
37     21.0
Name: MEDV, Length: 404, dtype: float64

In [5]:
X_test

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
307,0.04932,33.0,2.18,0,0.472,6.849,70.3,3.1827,7,222,18.4,396.90,7.53
343,0.02543,55.0,3.78,0,0.484,6.696,56.4,5.7321,5,370,17.6,396.90,7.18
47,0.22927,0.0,6.91,0,0.448,6.030,85.5,5.6894,3,233,17.9,392.74,18.80
67,0.05789,12.5,6.07,0,0.409,5.878,21.4,6.4980,4,345,18.9,396.21,8.10
362,3.67822,0.0,18.10,0,0.770,5.362,96.2,2.1036,24,666,20.2,380.79,10.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,0.04203,28.0,15.04,0,0.464,6.442,53.6,3.6659,4,270,18.2,395.01,8.16
224,0.31533,0.0,6.20,0,0.504,8.266,78.3,2.8944,8,307,17.4,385.05,4.14
110,0.10793,0.0,8.56,0,0.520,6.195,54.4,2.7778,5,384,20.9,393.49,13.00
426,12.24720,0.0,18.10,0,0.584,5.837,59.7,1.9976,24,666,20.2,24.65,15.69
443,9.96654,0.0,18.10,0,0.740,6.485,100.0,1.9784,24,666,20.2,386.73,18.85

In [7]:
y_test

307    28.2
343    23.9
47     16.6
67     22.0
362    20.8
       ...
92     22.9
224    44.8
110    21.7
426    10.2
443    15.4
Name: MEDV, Length: 102, dtype: float64

In [12]:
import xgboost 
import numpy as np
from sklearn.metrics import mean_squared_error


model = xgboost.XGBRegressor(random_state=0)

model.fit(X_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
             grow_policy='depthwise', importance_type=None,
             interaction_constraints='', learning_rate=0.300000012, max_bin=256,
             max_cat_threshold=64, max_cat_to_onehot=4, max_delta_step=0,
             max_depth=6, max_leaves=0, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=0,
             num_parallel_tree=1, predictor='auto', random_state=0, ...)

In [13]:
preds = model.predict(X_test)

In [14]:
preds

array([30.359884, 27.026636, 19.17616 , 21.448114, 20.703493, 20.424747,
       27.9036  , 17.878405, 21.678137, 23.36513 , 25.411674, 33.19199 ,
       21.495481, 19.939993, 19.990822, 28.529932, 13.219593, 44.483154,
       25.460302, 11.562899, 19.486588, 17.153116, 24.325785, 23.509218,
       27.791344,  8.616411, 14.683976, 19.01615 , 45.651524, 12.10203 ,
       22.976582, 17.523937, 48.34446 , 16.573458, 24.024517, 21.818398,
       14.679352, 35.878193, 16.073364, 20.764208, 25.262817, 22.376215,
       24.78839 , 14.799538, 16.877083, 11.262062, 46.995094, 11.280138,
       21.217411, 18.637756, 23.77302 , 20.691387, 25.980684, 20.501291,
        8.173699, 22.731295, 11.759897, 24.526464, 18.271172, 38.32712 ,
       12.570583, 25.870787, 12.011916, 13.295293, 17.679295, 35.901722,
       37.55958 , 23.164257, 20.201231, 20.955679, 24.68425 ,  7.049963,
       18.19561 , 19.824377, 19.77468 , 20.867382, 40.98662 , 24.473787,
       27.369884, 31.096327, 16.441713, 19.326612, 36.752098,  9.891363,
       20.98247 , 25.28127 , 14.024525, 26.155094, 21.51227 , 16.4159  ,
       23.28247 , 45.429245, 15.133404, 20.947332, 14.996857, 20.791437,
       24.775454, 23.958286, 45.176277, 22.56781 , 15.780695, 16.750847],
      dtype=float32)

In [15]:
rmse = np.sqrt(mean_squared_error(y_test, preds))

print("RMSE", round(rmse,2))

RMSE 3.01